spring:
    application:
        name: brewery-config
    profiles:
      ##  active: git
    cloud:
        config:
#            discovery:
#                enabled: true
            server:
                git:
                    #note on URI
                    uri: https://github.com/rafhael-s-p/mssc-brewery-config-repo/
                    clone-on-start: true
                   # username: rafhael-s-p
                    #Needed to setup search paths
                    search-paths: '{application}'
    security:
      user:
          password: myPassword
          name: myUserName
server:
    port: 8888
logging:
    level:
        org.springframework.cloud: debug
        org.springframework.web: debug
management:
    endpoint:
        health:
            show-details: always
        mappings:
            enabled: true